backend:
  name: github
  branch: development
  repo: ccollins1544/my-first-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }
  - name: team
    label: Team
    folder: src/team
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Team Member", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }
